language: python
python:
 - "2.7"
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libpcap-dev -y
 - sudo apt-get install -y build-essential libnetfilter-queue-dev
 - sudo apt-get -y install python-qt4 python-scapy python-nmap

sudo: required
install:
 - pip install flake8
 # stop the build if there are Python syntax errors or undefined names
 - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
 # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
 - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 - sudo pip install -r requirements.txt
 - sudo chmod +x installer.sh
 - sudo ./installer.sh --install

script: exit 0
